# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ecom-shop-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_05064f6c9ceb4e51bc62696dc270b058 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ae27efbc6dfd4838b81fd896feef3b4b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05064f6c9ceb4e51bc62696dc270b058 }}/ecommerceapi:container_${{ github.sha }}
        file: ./EcommerceApi/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecom-shop-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a205ac5843414e7cbc0ed0ff299cddc3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05064f6c9ceb4e51bc62696dc270b058 }}/ecommerceapi:container_${{ github.sha }}'
