# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ecom-general-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5dfdb6bd334a4ca39ef367f4455ada3e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d0a06089a49945c8ac8e06dbb2665d84 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5dfdb6bd334a4ca39ef367f4455ada3e }}/freemangn/ecommerceapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecom-general-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_36fa86707ed347d28ef3084cfa0ddce1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5dfdb6bd334a4ca39ef367f4455ada3e }}/freemangn/ecommerceapi:${{ github.sha }}'