# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ecom-shop-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_05064f6c9ceb4e51bc62696dc270b058 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ae27efbc6dfd4838b81fd896feef3b4b }}

    - name: Build and push container image to Docker hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05064f6c9ceb4e51bc62696dc270b058 }}/ecommerceapi:container_${{ github.sha }}
        file: ./EcommerceApi/Dockerfile

  Generate_sql_script:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4
    - name: Install dotnet ef tool
      run: dotnet tool install --global dotnet-ef

    - name: Generate scripts
      run: dotnet ef migrations script --output ./sql/sql-script.sql --idempotent --context AppDbContext -p EcommerceApi

    - name: Azure SQL Deploy 
      uses: Azure/sql-action@v2.2
      with:
          server-name: tcp:ecom-shop-api.database.windows.net
          connection-string: ${{ secrets.DB_CONNECTION }}
          path: './sql/sql-script.sql'

  Deploy:
    runs-on: ubuntu-latest
    needs: Generate_sql_script
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecom-shop-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a205ac5843414e7cbc0ed0ff299cddc3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05064f6c9ceb4e51bc62696dc270b058 }}/ecommerceapi:container_${{ github.sha }}'
